### ISSUE TITLE
Supporting DS1307

### ISSUE THREAD

**Issue by jamesle-0812** [sparkslabs/pyxie#26]
Hi, I'm really interested in your project. It's amazing.  My issue is I'm using Arduino Leonardo with a DS1307. Does your project support my case? Thanks in advance.

**Comment by sparkslabs** [comment]
(Only just seen this)

What is a DS1307? I2C RTC?

It's relatively easy to get random hardware working - take a look in https://github.com/sparkslabs/pyxie/blob/master/pyxie/profile/arduino.py

You need to define in there any function calls you use, the types, and any constants & their types you use.

Whether that's enough for your device I don't know. ( I don't have a DS1307)

Hope that's useful.

**Comment by sparkslabs** [comment]
Closing - lack of response
