### ISSUE TITLE
Pyxie on Windows?

### ISSUE THREAD

**Issue by AaroAaron** [sparkslabs/pyxie#30]
I have installed the Pyxie in my Windows system, but I have no idea about running the command "pyxie compile demo.pyxie". 
Is this bucause the Pyxie only runs on Linux?

**Comment by sparkslabs** [comment]
Pyxie at present doesn't support windows, due to the fact that I don't use windows at present. Supporting Windows isn't currently on my radar. 

You're welcome to provide patches, and I can review them, but Windows is not a priority for me right now.

**Comment by AaroAaron** [comment]
got it，and thank you for your reply!
